services:
  thetaterm:
    image: thetaterm:latest
    restart: always
    ports:
      - "127.0.0.1:25503:25503"
    environment:
        THETADATA_CREDS_FILE: /run/secrets/thetadata_creds
    secrets:
      - thetadata_creds
    build:
      dockerfile: ./Dockerfile

secrets:
  thetadata_creds:
    file: thetadata-creds.txt
